

services:


  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: umassgrades
      POSTGRES_PASSWORD: secret
    volumes:
      - umassgrades-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  umassgrades-pg-local:
